### ISSUE TITLE
code copied from CryptoSwift

### ISSUE THREAD

**Issue by krzyzanowskim** [diejmon/ServerSideSwifter#1]
Hey, I found you copied my code from [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) project and don't follow the licence of the original code. Is there a reason to do so?

**Comment by diejmon** [comment]
Please make a pull request with the things I missed to add. Not an expert in licences. 

Or describe what the changes  are needed.

**Comment by krzyzanowskim** [comment]
[License](https://github.com/krzyzanowskim/CryptoSwift#license) says
> The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation is required.

please follow this. thanks.
